project:
  type: website
  output-dir: docs 

website:
  title: "Learning to Sieve Data"
  description: "Another blog"
  navbar:
    right:
      - text: Posts 
        href: blog.qmd
      - index.qmd
      - icon: github
        href: https://github.com/tyvan266
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: journal
    css: styles.css

editor: visual

